name: 'deploying-marker-with-issue'
description: 'This action checks, applies and removes the "Deploying" label of GitHub Issue that indicating the deployment status.'
author: 'Connehito'
inputs:
  action:
    required: true
    description: 'check-marker, add-marker or remove-marker'
  issue-number:
    required: true
    description: '(TODO)'
runs:
  using: 'node16'
  main: 'dist/index.js'
