name: 'deploying-marker-with-issue'
description: 'This action checks, applies and removes the "Deploying" label of GitHub Issue that indicating the deployment status.'
author: 'Connehito'
inputs:
  action:
    required: true
    description: 'Specify `check-marker`, `add-marker` or `remove-marker`'
  issue-number:
    required: true
    description: 'The issue number of the GitHub Issue for labeling'
  exit-with-error:
    required: false
    description: 'Exit with an error depending on the label status.'
    default: "true"
runs:
  using: 'node16'
  main: 'dist/index.js'
