name: 'example'
on: push

jobs:
  example: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: Connehito/deploying-marker-with-issue@main
        with:
          action: "check-marker"
          issue-number: 12
          exit-with-error: true # true = exit with error when the marker is not found
      - uses: Connehito/deploying-marker-with-issue@main
        with:
          action: "add-marker"
          issue-number: 12
          exit-with-error: true # true = exit with error when the marker is already exists
      - uses: Connehito/deploying-marker-with-issue@main
        with:
          action: "remove-marker"
          issue-number: 12
          exit-with-error: false # true = exit with error when the marker is not exists
