name: 'example'
on: push

env:
  DEPLOYMENT_RECORD_ISSUE_NUMBER: 21

jobs:
  example: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: Connehito/deploying-marker-with-issue@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          action: "check-marker-detached"
          issue-number: ${{ env.DEPLOYMENT_RECORD_ISSUE_NUMBER }}
          exit-with-error: true # true = exit with error when the marker is already exists
      - uses: Connehito/deploying-marker-with-issue@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          action: "attach-marker"
          issue-number: ${{ env.DEPLOYMENT_RECORD_ISSUE_NUMBER }}
          exit-with-error: true # true = exit with error when the marker is already exists
      - name: Sleep 30s
        run: sleep 30
      - uses: Connehito/deploying-marker-with-issue@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          action: "check-marker-attached"
          issue-number: ${{ env.DEPLOYMENT_RECORD_ISSUE_NUMBER }}
          exit-with-error: false # true = exit with error when the marker is not exists
      - uses: Connehito/deploying-marker-with-issue@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          action: "detach-marker"
          issue-number: ${{ env.DEPLOYMENT_RECORD_ISSUE_NUMBER }}
          exit-with-error: false # true = exit with error when the marker is not exists
