name: 'example'
on: push

jobs:
  example: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: Connehito/deploying-marker-with-issue@main
        with:
          action: "check-marker"
          issue-number: 12
