name: 'example'
on: push

jobs:
  example: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: Connehito/deploying-marker-with-issue@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          action: "check-marker-detached"
          issue-number: 12
          exit-with-error: true # true = exit with error when the marker is not found
      - uses: Connehito/deploying-marker-with-issue@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          action: "attach-marker"
          issue-number: 12
          exit-with-error: true # true = exit with error when the marker is already exists
      - name: Sleep 10s
        run: sleep 10
      - uses: Connehito/deploying-marker-with-issue@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          action: "check-marker-attached"
          issue-number: 12
#          exit-with-error: true # true = exit with error when the marker is found
          exit-with-error: false
      - uses: Connehito/deploying-marker-with-issue@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          action: "detach-marker"
          issue-number: 12
          exit-with-error: false # true = exit with error when the marker is not exists
